name: Run Robot Framework Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install robotframework selenium robotframework-seleniumlibrary
       sudo apt-get update
       sudo apt-get install -y chromium-browser chromium-chromedriver
       sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome

    - name: Run Robot Framework Tests
      env:
        ROBOT_BROWSER: headlesschrome
      run: |
        robot tests/elonmusk.robot
