name: Robot Framework Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.3'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Chrome and chromedriver (untuk Selenium)
      - name: Install Chrome and ChromeDriver (v136)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chromedriver/136.0.7103.49/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
        
      # Run Robot Framework tests with Chrome options
      - name: Run Robot Framework tests
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          robot test/elonmusk.robot
