name: Robot Framework Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.3'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Chrome & Chromedriver (auto compatible)
      - name: Install Chrome and Chromedriver
        run: |
         sudo apt-get update
         sudo apt-get install -y wget curl unzip gnupg
         curl -sSL https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/google.gpg
         echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
         sudo apt-get update
         sudo apt-get install -y google-chrome-stable
         CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
         DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r --arg ver "$CHROME_VERSION" '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
         wget -O chromedriver.zip "$DRIVER_VERSION"
         unzip chromedriver.zip
         sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
         sudo chmod +x /usr/local/bin/chromedriver

      # Run Robot Framework tests (headless)
      - name: Run Robot Framework Tests
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          robot test/elonmusk.robot
