name: Run Robot Framework Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework selenium robotframework-seleniumlibrary

        # Install Google Chrome
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get update
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb || sudo apt-get --fix-broken install -y

        # Install ChromeDriver matching Chrome version
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q -O chromedriver.zip "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Run Robot Framework Tests (headless)
      env:
        ROBOT_BROWSER: headlesschrome
      run: |
        robot --outputdir results tests/
