name: Run Robot Framework Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework selenium robotframework-seleniumlibrary

    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get update
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb || sudo apt-get --fix-broken install -y

    - name: Install ChromeDriver matching Chrome version
      run: |
        sudo apt-get install -y jq

        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        echo "Detected Chrome version: $CHROME_VERSION"

        DRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" \
          | jq -r --arg ver "$CHROME_VERSION" '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')

        echo "Downloading ChromeDriver from: $DRIVER_URL"
        wget -q -O chromedriver.zip "$DRIVER_URL"
        unzip chromedriver.zip
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Debug Information
      run: |
        google-chrome --version
        chromedriver --version
        pip freeze
        ls -la tests/

    - name: Run Robot Framework Tests (headless)
      env:
        ROBOT_BROWSER: headlesschrome
      run: |
        export ROBOT_BROWSER_OPTS="--no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=1920,1080"
        robot --outputdir results --loglevel DEBUG tests/

    - name: Upload Robot Framework Results
      uses: actions/upload-artifact@v3.1.2
      with:
        name: robot-results
        path: results/
